### ISSUE TITLE
Расширение для платы

### ISSUE THREAD

**Issue by LowderPlay** [Yevgeniy-Olexandrenko/aym-streamer#1]
Приветствую! Собрал ваше устройство, большое спасибо, играет классно. 
Заметил на плате порт расширения. Планируется ли вторая плата с SD-картой и дисплеем, чтобы воспроизводить без подключения к ПК? 

P.S. Вот фото моего устройства.
![image](https://user-images.githubusercontent.com/22765741/193868784-5e5b88a1-843c-4096-87ce-1718d95ed515.png)

**Comment by Yevgeniy-Olexandrenko** [comment]
Здравствуйте!

Очень рад, что вы во всем разобрались и самостоятельно собрали устройство. Очень необычно видеть его в чужом исполнении :) Было бы неплохо увидеть фото самой платы без корпуса с обоих сторон.

Что касается расширения, вы правы. В плату заложена возможность расширить ее функции дополнительной платой сверху. Я даже начинал ее проектировать. Предполагалось, что на этой плате будет слот для SD, i2c дисплей, 3-4 кнопки управления и i2c дигипод(ы) для управления громкостью. В теории устройство можно сделать полностью автономным. снабдив его аккумулятором и схемой зарядки. 

Так же у меня к вам встречный вопрос: какой программой вы пользуетесь для воспроизведения? Специально для этого устройства я начал разрабатывать свою программу PSG Tools. Она сейчас находится в ранней альфа стадии, но уже умеет много всякого интересного. Например, полноценно поддерживает чип AY8930 как в эмуляции, так и установленный в AYM Streamer.

**Comment by LowderPlay** [comment]
Добрый день. Сделал фотографии устройства как вы просили. Очень понравилась ваша трассировка печатной платы. Стример запустился сразу и очень хорошо играет. Благодаря операционному усилителю звук стал намного сочнее чем с AY-3-8910 напрямую. При заказе печатной платы торопился и забыл указать "номер заказа в указанном месте". По этому, на плате есть соответствующая шелкография :)  Но это не бросается в глаза из-за не прозрачной задней стенки. Спасибо вам большое за проделанную работу.

По поводу программного обеспечения. Я использую стример в связке с AVR-AY Player версии 13.7. Меня устраивает его работа и интерфейс в целом. Вашей программой пока не пользовался. AVR-AY Player был найден мной ранее в интернете. На нем и остановил пока свой выбор. Я пока только начинаю разбираться в формате файлов и у меня нет каких-то особых требований к ПО. В дальнейшем планирую создавать свои композиции, но это в очень далёком будущем. Сборка стример - это первый шаг на этом интересном пути. Но недавно в AVR-AY Player был замечен баг с зависанием при использовании более 2 часов. Теряется связь со стримером. Невозможно открыть виртуальный COM порт. Даже после закрытия всех возможных процессов. Помогает лишь перезагрузка компьютера. Не понял только с какой стороны эта проблема. 
AVR-AY Player, прошивка в ATmega или не корректная работа USB-UART моста. 

Скажите пожалуйста, вы планируете продолжить работу над платой расширения для стримера? Очень хотелось бы получить портативный вариант для прослушивания в машине, на улице, на природе. В каком состоянии находится сейчас данная часть проекта?

Прикладываю фотографии платы
![IMG_20221006_162736_146.jpg](https://user-images.githubusercontent.com/22765741/194301333-4dcae04d-71f5-4ef2-be83-4dbb7ddbf22e.jpg)
![IMG_20221006_162733_600.jpg](https://user-images.githubusercontent.com/22765741/194301348-d127a9f1-40e0-434e-82fb-f9bb0a947f00.jpg)
![IMG_20221006_162731_391.jpg](https://user-images.githubusercontent.com/22765741/194301386-439512c4-cdab-4c79-a221-3621ca84ca11.jpg)

**Comment by Yevgeniy-Olexandrenko** [comment]
Здравствуйте. Спасибо за фото. Еще интересно как у вас получилась аналоговая часть, что под чипом. Но по фото видно качественную пайку, будто я сам паял. В этом устройстве, в отличие от аналогичных разработок, особое внимание уделено аналоговой части, аналоговому питанию и максимально корректной разводке платы. Рад что у меня получилось достичь хорошего звука из AY.

AVR-AY Player я и сам раньше использовал, собственно под него стример и делался. Но в процессе эксплуатации у программы было выявлено несколько серьезных косяков. Я попытался связаться с автором, описал у него на сайте некоторые проблемы, но никакого ответа не получил. Исходников нет, при всем моем желании я не могу это починить самостоятельно. В итоге я решил разрабатывать собственную программу для проигрывания и конвертации музыки под AY-3-8910/YM2149, благодаря чему получил нужные мне возможности и приобрел огромный опыт по работе с этими чипами и не только.

По поводу отвала COM порта в AVR-AY Player. Мне кажется, я сталкивался с похожими проблемами. Но я уже почти год не пользуюсь этим проигрывателем,  а при проигрывании в моем PSG Tools вроде бы такого не встречал. Но точно не скажу, надо будет поставить проигрывание на несколько часов и посмотреть.

Плата расширения сейчас не в первом приоритете. Нужны эксперименты, свободное время. Но сейчас даже с заказом плат огромные проблемы, так как JLCPCB более не доставляет напрямую к нам. В ближайших планах есть желание сделать новую версию платы стриммера с незначительными изменениями и серьезно переработать firmware для расширения функциональности при работе с PSG Tools. Если есть какие-то дельные мысли по улучшению схемы или платы самого стриммера - можно обсудить и добавить в намечающуюся новую версию.
